### ISSUE TITLE
Wrong file name in linux

### ISSUE THREAD

**Issue by AmirHosein-Gharaati** [reza00farjam/rjdl#2]
By downloading a music, I got a wrong-song-name in the directory I was working with :

![Screenshot from 2020-08-06 19-16-19](https://user-images.githubusercontent.com/56169125/89546493-ea9a8a80-d819-11ea-83b2-5c993a2cbab7.png)

**Comment by reza00farjam** [comment]
fixed in new version 0.1.1, tnx for reporting.
