### ISSUE TITLE
Not working - rjdl: error: this quality isn't available

### ISSUE THREAD

**Issue by Saman24** [reza00farjam/rjdl#5]
Hi,
Thank you for the script, but when I try to download a playlist or a song it says "rjdl: error: this quality isn't available"
no matter if I select 256 or 320.
can you please take a look? Thank you

**Comment by reza00farjam** [comment]
Hi @Saman24 
Thanks a lot for ur report and feedback <3
The problem was due to restructure of music web page on RJ. It is now fixed on version 1.0.1 that u can upgrade to it via:   
`pip install rjdl --upgrade`
